### ISSUE TITLE
Update in plantuml-stdlib, request to tag version

### ISSUE THREAD

**Issue by Potherca** [tupadr3/plantuml-icon-font-sprites#12]
Hi! I've opened an MR in `plantuml-stdlib`to update this project there: https://github.com/plantuml/plantuml-stdlib/pull/13

It looks like [changes have been made](https://github.com/tupadr3/plantuml-icon-font-sprites/compare/v2.0.0...master) since the `*.puml` files were last updated in plantuml-stdlib, but since there is no new version was tagged, I can't automate this any further.

Would it be possible to git tag the latest changes in master? (The documentation mentions v2.1.0)

**Comment by tupadr3** [comment]
v2.1.0 is available

**Comment by Potherca** [comment]
Awesome, many thanks!
