### ISSUE TITLE
how to set background color and font size on these sprites?

### ISSUE THREAD

**Issue by titaniumbones** [tupadr3/plantuml-icon-font-sprites#13]
Is it possible to add some details explaining how to change background-color (and transparency if possible), border style, and label font size to these sprites? Thank you so much!

**Comment by graham2071** [comment]
Hello, i was wondering the same thing. After some search, this is quite simple. Do not use the macros, use `scale` directly on the sprite.

Example

```plantuml
@startuml size_matters

!include <tupadr3/common>
!include <tupadr3/devicons/linux>

rectangle "<$linux{scale=0.5}>hi"
rectangle "<$linux{scale=2}>HELLO!"

@enduml
```
