### ISSUE TITLE
How to make this work with plantuml -Sdpi 300?

### ISSUE THREAD

**Issue by nolith** [tupadr3/plantuml-icon-font-sprites#14]
Hello 👋 

thank you so much for making this.

I'm working on a graph that is rendered using `plantuml -Sdpi300 file.txt`, but the result is that the icons looks stretched.

![architecture](https://user-images.githubusercontent.com/78752/73256813-ec2c2b80-41c2-11ea-8555-3100a68bad1a.png)

Do you know how can I fix this?

```
@startuml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.1.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/dev2/redis.puml

frame "Redis" {
  DEV2_REDIS(queues) #White
}

frame "Load Balancer" {
 HTTPS - [Proxy]
}

frame "Web" {
  [Server] as ruby
  HTTP - [ruby]
  [Proxy] ..> HTTP
  [ruby] ..> [queues]  : enqueue a job
}

frame "Async" {
  [Queue processor] ..> [queues] : dequeue a job
}

@enduml
```

**Comment by tupadr3** [comment]
Probably an resolution and sclaing issue. You may need a higher resolution for your sprites.
