### ISSUE TITLE
Missing FA5 network-wired

### ISSUE THREAD

**Issue by pdugas** [tupadr3/plantuml-icon-font-sprites#15]
The Font-Awesome v5 [network-wired](https://fontawesome.com/icons/network-wired) icon is missing.

**Comment by pdugas** [comment]
Missing [ethernet](https://fontawesome.com/icons/ethernet) too.

**Comment by tupadr3** [comment]
Latest version includes the latest icons:
[sample-puml-with-network-wired](http://www.plantuml.com/plantuml/png/ROr1ImCn44Rl-HNfJG-RIAKNJorQeIWjB9KUbvXCkw7994mc6t--g-99hz_ZlMzTs13N64IvUio6J9GEpgO6Fi87RuA_O0HaQG4PI8Z5J3s2t3qUzc_zgnoPStdGcanJ5yzZVQy5o2PaG5OsHSqr6qVtEWU3Nq-TdsbtJiXToUGPYfwMQgdknCAZ3TL1fV3RrpR5c53bMVoNVtTCWv8YT2kDm2tHTMYUmFrOWZq7aC-RrR3V7a-7_cKuxVhjan1_ffis6eO9w5Qi0TriVm80)

**Comment by pdugas** [comment]
Thanks much.
