### ISSUE TITLE
Update the references to DEVICON2

### ISSUE THREAD

**Issue by cilerler** [tupadr3/plantuml-icon-font-sprites#17]
DEVICON2 has new icons, please update the references

**Comment by tupadr3** [comment]
@cilerler Done.

**Comment by cilerler** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/ed5c9c0f-c444-4b15-b96b-a66885184e6a-ccdabca3-9682-4342-aa5e-1222b8adc35f-v1.png?transparent=1&palette=1&width=246)
Thank you!
