### ISSUE TITLE
Add Kotlin to devicons

### ISSUE THREAD

**Issue by akcorp2003** [tupadr3/plantuml-icon-font-sprites#18]
Can we add Kotlin language to the devicons? The icon looks like [this](https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Kotlin-logo.svg/1200px-Kotlin-logo.svg.png).

**Comment by tupadr3** [comment]
Take look at https://github.com/tupadr3/font-icon-generator. This is the src which generated the sprites for this project. You're welcome to add a new source for sprites which contains a flutter icon
