### ISSUE TITLE
Add flutter to devicons2

### ISSUE THREAD

**Issue by ofw** [tupadr3/plantuml-icon-font-sprites#19]
https://flutter.dev/

**Comment by tupadr3** [comment]
Take look at https://github.com/tupadr3/font-icon-generator. This is the src which generated the sprites for this project. You're welcome to add a new source for sprites which contains a flutter icon

**Comment by tupadr3** [comment]
@ofw Version 2.3.0 contains the latest devicons2. The flutter icon is now available.
