### ISSUE TITLE
Integrate PlantUML Icon-Font Sprites icons into PlantUML 

### ISSUE THREAD

**Issue by arnaudroques** [tupadr3/plantuml-icon-font-sprites#2]
Many thanks for your contribution!
If you are ok with the idea, we would like to include your library into the standard distribution of PlantUML.
(so in https://github.com/plantuml/plantuml/tree/master/stdlib like we have done for https://github.com/milo-minderbinder/AWS-PlantUML/issues/20 )

That way, people would be able to use it out-of-the box with the following syntax:

```
!include <devicons/common>
!include <devicons/mysql>
!include <font-awesome/database>
```

Your repository would still be the official source for this library: we would just duplicate files into our repository.

What do you think about it ?

**Comment by tupadr3** [comment]
Thx. Many thanks to you guys for plantuml.

That would be awesome.

**Comment by arnaudroques** [comment]
This is now included in V1.2017.19
For example http://www.plantuml.com/plantuml/uml/TP5VIyCm5CNVyodkyC49hMNjdcIKTTZ9OC9eTU2JfCjr2wH9QMwj-_OcpZdxi9V0oU-SS_DdRectrDMAtS96SKslpskm99IiG9iUfDwfJg25rSxeS6aqGTcqaj2Ee4I40r5Z7w9eB-dGLVSxKqVKDLoqITJuEjSSIX_zSD7GdgACZNvxOVQpptkqfiR8nMkZqslOOlk9xLKiEF6AMqmP8qaAeQIZadeF-CNhHY5Zo-ozp8jjNenxh2Q1N-xWvgb5r4CMUnOxzePAcNu84myJ1nUgmo6QUZJzovsQlUKnUyaMMPcFXPkxNctpu7pQe3-uDt6HmXovEbV-yyT1kScAIy1RKJ3ccc0MXYau2sF-BcSvyIeUg6IWfXV5vgY5__zl

**Comment by albert-github** [comment]
@arnaudroques the given example doesn't work anymore, any update?

**Comment by arnaudroques** [comment]
The syntax is now http://www.plantuml.com/plantuml/uml/XOvHIyCm58NVyolkyC49hMNjdcICTTZ9OC9eTU2JfCjr2wH9QMwj-_ScpbagWY-1mtU-axkmn1jgAyMkOQkufkV73LWIIfQWJGTIxrKhqC9wRtIuCfgWg1j9Q4TG8CAHgBPtKNIGT6pBsxsf8cfhBfeagjsSNmwbLz-S6jgpojZeUnTcbxOpAwFdVv0latTeJOMHnUOTctzhWXClkSKvOoH98HHqKb8V03zuLIjaR9M-5bc-o_9nX-KayCyDN3qqY7h8OizYnrvGATCDOU9Xuk1IjJX4Ku-cFzvvsLVkqwTqcHRPMBX_D-jT5bok3RgZ97HARavS-SbV_JWejcdU2xwAWZ6t1BCmd8EhCDPX7oS-nOEK3DAqJmlKegtK9m00
