### ISSUE TITLE
Join https://github.com/plantuml-stdlib and/or migrate there?

### ISSUE THREAD

**Issue by Potherca** [tupadr3/plantuml-icon-font-sprites#20]
Several of us have been making an effort to bring together the projects and people who feed sprites into the official [plantuml-stdlib](https://github.com/plantuml/plantuml-stdlib/).

We've been doing this under https://github.com/plantuml-stdlib/, with the go-ahead of Arnaud Roques (creator of PlantUML)

This ticket is to ask whether you would be interested in joining that effort and/or migrating this project to the PlantUML-StdLib organization.

The main reason for asking is to see if, by joining forces, we can make sure that any sprites already added to the official plantuml-stdlib remain maintained.

So, what do you think?

**Comment by tupadr3** [comment]
> This ticket is to ask whether you would be interested in joining that effort and/or migrating this project to the PlantUML-StdLib organization.

I'll think about it.

**Comment by Potherca** [comment]
@tupadr3  Any thoughts yet?

**Comment by tfc** [comment]
@tupadr3 I've started to use plantuml+c4-stdlib+iconlib extensively at work and packaged these 3 things together into an integrated `plantuml` call: https://github.com/NixOS/nixpkgs/pull/192483

This would be nicer to maintain due to less individual parts if it was part of c4-stdlib already.

**Comment by Potherca** [comment]
@tupadr3  This is your friendly one-year-later reminder to ask if you might be interested.
