### ISSUE TITLE
Include other font library from Templarian MaterialDesign

### ISSUE THREAD

**Issue by harderal** [tupadr3/plantuml-icon-font-sprites#22]
Is there a way to include the Templarian MaterialDesign icon collection into PlantUML? There is a large and amazing collection of icons to choose from and very relevant to modern use cases - https://github.com/Templarian/MaterialDesign

**Comment by Potherca** [comment]
An older (2017)  version of the Templarian Material Design icons is already available in PlantUML natively (through [plantuml-stdlib/](https://github.com/plantuml/plantuml-stdlib/)).

To have a more up-to-date version included, I would suggest opening an issue there to make your interest known.

The available icons appear to be:

[![](https://raw.githubusercontent.com/gist/Potherca/e26695a08ff7a8e0a97e6502f1fe2f40/raw/all-material-icons.svg)](https://gist.github.com/Potherca/e26695a08ff7a8e0a97e6502f1fe2f40)

**Comment by tupadr3** [comment]
@harderal Take look at https://github.com/tupadr3/font-icon-generator. This is the src which generated the sprites for this project. You're welcome to add a new source for sprites
