### ISSUE TITLE
Add icon for cockroach DB and Kafka

### ISSUE THREAD

**Issue by darielrll** [tupadr3/plantuml-icon-font-sprites#23]
https://www.cockroachlabs.com/
https://kafka.apache.org/

**Comment by darielrll** [comment]
@tupadr3 thanks a lot for your amazing work here? Is it possible that you tell me the steps you follow to generate the `.puml` file and the `.png` file for those new tools ?
If you provide me the instructions I can generate a pull request.
Thanks in advance.

**Comment by tupadr3** [comment]
@darielrll Check out https://github.com/tupadr3/font-icon-generator. This is the project which generated the sprites for this project
