### ISSUE TITLE
repo uses deprecated `!includeurl` and `!define`

### ISSUE THREAD

**Issue by scmbradley** [tupadr3/plantuml-icon-font-sprites#24]
The [PlantUML page on preprocessing](https://plantuml.com/preprocessing) suggests that  `!includeurl` and `!define` are legacy features. I guess it would be good to move to using the currently recommended syntax for procedures etc.

**Comment by christo-ph** [comment]
Alternatives?

**Comment by scmbradley** [comment]
`!include` now [apparently](https://plantuml.com/preprocessing#393335a6fd28a804) allows inclusions from URLs, so `!includeurl` is obsolete. `!define` should [apparently](https://plantuml.com/preprocessing#0625790a47906fd3) be replaced by `!procedure`.

**Comment by scmbradley** [comment]
The following works.

```
@startuml
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0"
!include $ICONURL/common.puml
!include $ICONURL/devicons/mysql.puml

DEV_MYSQL(d1)
@enduml

```

So wrap the URL in quote marks, and use a `=` when defining a variable.

**Comment by victorng8** [comment]
Why is the official readme still not updated with this new modified version?

**Comment by tupadr3** [comment]
The proposed changes have been implemented
