### ISSUE TITLE
add/update icons to DevIcon's latest

### ISSUE THREAD

**Issue by cilerler** [tupadr3/plantuml-icon-font-sprites#26]
Since your [last update](https://github.com/tupadr3/plantuml-icon-font-sprites/issues/17), the [DevIcon](https://github.com/devicons/devicon/releases/tag/v2.14.0) has added 80+ new icons.  Please add/update those to the repository.

**Comment by tupadr3** [comment]
Updated to v2.12.0. 

For newer versions a change in https://github.com/tupadr3/plantuml-icon-font-sprites/blob/master/src/lib/handler/dev2.js would be required as the source css file for the icon names was removed.
