### ISSUE TITLE
Feature Request - New Sprite - Apache Ignite

### ISSUE THREAD

**Issue by axiopisty** [tupadr3/plantuml-icon-font-sprites#27]
I would like to request a new sprite be added for the Apache Ignite database.

See: https://ignite.apache.org/

**Comment by mihaigalos** [comment]
I think you can provide a PR with the request by:
* creating the icon.png *exactly* 48x48 pixels.
* running `plantuml -encodesprite 16 icon.png > result.puml`.
* add the `@startuml` prefix before the generated `result.puml`
* add the following suffix at the end of `result.puml`:

```plantuml
!define DEV2_MYMACRO(_alias) ENTITY(rectangle,black,aftereffects,_alias,DEV2 MYMACRO)
!define DEV2_MYMACRO(_alias, _label) ENTITY(rectangle,black,aftereffects,_label, _alias,DEV2 MYMACRO)
!define DEV2_MYMACRO(_alias, _label, _shape) ENTITY(_shape,black,aftereffects,_label, _alias,DEV2 MYMACRO)
!define DEV2_MYMACRO(_alias, _label, _shape, _color) ENTITY(_shape,_color,aftereffects,_label, _alias,DEV2 MYMACRO)
skinparam folderBackgroundColor<<DEV2 MYMACRO>> White
@enduml
```

This^ can be automated but would still require the input 48x48 pixel input PNG file.

**Comment by Potherca** [comment]
Icon request has been submitted to Dev Icons: https://github.com/devicons/devicon/issues/1552
