### ISSUE TITLE
Searchable HTML overview of existing icons

### ISSUE THREAD

**Issue by tfc** [tupadr3/plantuml-icon-font-sprites#29]
Hi,

in order to have it easier selecting icons from this great plantuml icon font sprites library, i created myself a nice little HTML overview of all items that are available in this runner:

![Screenshot from 2022-09-30 11-46-49](https://user-images.githubusercontent.com/29044/193243491-f41dd843-7851-4505-b294-fdc8cf309d74.png)

The overview is generated with a python script that can be rerun anytime if the icon collection is extended
It might be a nice addition to this library/github repo if the generated output would be shared online (e.g. github pages feature).
I can help doing that but i wanted to ask if there is interest in this at all.

The python script:

```python
#!/usr/bin/env python3

import os


def all_puml_files_iterator(root_dir):
    return (
        os.path.join(dp, f)
        for dp, dn, filenames in os.walk(root_dir)
        for f in filenames
        if os.path.splitext(f)[1] == ".puml"
    )


def get_folder_and_name(puml_file_path):
    relpath = os.path.relpath(puml_file_path)
    return os.path.dirname(relpath), os.path.splitext(os.path.basename(relpath))[0]


paths_and_names = map(get_folder_and_name, all_puml_files_iterator("."))

items_dict = {}
for path, name in paths_and_names:
    items_dict[path] = items_dict.get(path, []) + [name]
items_dict.pop("")

print(
    """
<html>
  <head>
    <title>Plantuml Icon Font Sprites Overview</title>
    <style>
    .cards {
      display: flex;
      flex-wrap: wrap;
      align-items: stretch;
    }
    .card {
      flex: 0 0 200px;
      margin: 10px;
      border: 1px solid #ccc;
      box-shadow: 2px 2px 6px 0px  rgba(0,0,0,0.3);
    }
    .card img {
      max-width: 100%;
      margin-left: auto;
      margin-right: auto;
      display: block;
      padding-top: 10px;
    }
    .card .text {
      padding: 0 20px 10px;
    }
    pre {
      font-size: small;
    }
    </style>
  </head>
  <body>
"""
)

for folder, names in items_dict.items():
    print(
        f"""
    <h1>Folder "{folder}"</h1>
    <main class="cards">
"""
    )
    for name in names:
        print(
            f"""
      <article class="card">
        <img src="{folder}/{name}.png">
        <div class="text">
          <h2>{name}</h2>
          <pre>
!include common.puml
!include {folder}/{name}.puml</pre>
        </div>
      </article>
"""
        )

    print(
        """
    </main>
    <hr/>
"""
    )

print(
    """
  </body>
</html>
"""
)
```

**Comment by mihaigalos** [comment]
Hi @tfc, this is awesome. Please open a PR so that the maintainers can review and merge it.

**Comment by mihaigalos** [comment]
btw: please tag me in the PR so I can also contribute / improve if I see anything.
I would open it myself, the glory is however yours! :smile:

**Comment by tfc** [comment]
Oh, interesting. What do i need the macros for? I just use the titles of these items in my plantum descriptions (i.e. `moon_25` and not `WEATHER_MOON_25`)

**Comment by mihaigalos** [comment]
The titles are the `*.puml` files where the sprite is defined.
The macros are how to actually use them in PlantUML code.

Example:
[This](https://github.com/mihaigalos/docker/blob/f91d27e032845999205f0d585aaebe74d99dd9fe/ssh-pam/docs/diagram.puml#L25) uses the `DEV2_SSH_ORIGINAL_WORDMARK` defined [there](https://github.com/tupadr3/plantuml-icon-font-sprites/blob/e53fd61259c0f2449edfe304cad83f51d0fbb5c1/devicons2/ssh_original_wordmark.puml#L54-L57) to produce [that](https://camo.githubusercontent.com/7f90b144a13ee1973375d667692022417c8f6a22392fa6ab33681182d67c739e/687474703a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f70726f78793f63616368653d6e6f267372633d68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d6968616967616c6f732f646f636b65722f6d61737465722f7373682d70616d2f646f63732f6469616772616d2e70756d6c) PlantUML diagram.

**Comment by tupadr3** [comment]
@tfc I integrated it into the project. Take a look at [index.html](https://github.com/tupadr3/plantuml-icon-font-sprites/blob/v3.0.0/icons/index.html)
