### ISSUE TITLE
FA_PODCAST not included

### ISSUE THREAD

**Issue by 27escape** [tupadr3/plantuml-icon-font-sprites#3]
This is a piece of work, I am already adding it into my plantUML diagrams, many thanks for all your hard work.

I cannot see the podcast icon, is this intentional or an oversight?

    !include <font-awesome/common>
    !include <font-awesome/globe>
    !include <font-awesome/podcast>
    FA_PODCAST( pod1, "Podcast")
    FA_GLOBE( globe, "The world")
    pod1 -> globe
   
Cannot include <font-awesome/podcast>

**Comment by tupadr3** [comment]
Probably an oversight. I'll try to take a look during the weekend.

**Comment by 27escape** [comment]
Fantastic, thank you
