### ISSUE TITLE
Feature request - New Sprite - Scrapy

### ISSUE THREAD

**Issue by Alireza-Farahani** [tupadr3/plantuml-icon-font-sprites#30]
Scrapy is one the most famous crawler framework out there. It would be great to be included here.

[Scrapy site](scrapy.org)

**Comment by Potherca** [comment]
This project includes icons from various upstream projects:

- [Font-Awesome 4](https://fontawesome.com/v4.7.0/)
- [Font-Awesome 5](http://fontawesome.io/)
- [Devicons](http://vorillaz.github.io/devicons)
- [Govicons](http://govicons.io/)
- [Weather](https://erikflowers.github.io/weather-icons/)
- [Material](http://google.github.io/material-design-icons/)
- [Devicon 2](https://github.com/devicons/devicon.git)

For the Scrapy icon to be included here, it will first have to be added to one of those projects.

**Comment by mihaigalos** [comment]
Also, [FYI](https://github.com/tupadr3/plantuml-icon-font-sprites/issues/27#issuecomment-1297591784).

**Comment by Potherca** [comment]
Icon request has been submitted to Dev Icons: https://github.com/devicons/devicon/issues/1477
