### ISSUE TITLE
Could you convert the PNG images to SVG images?

### ISSUE THREAD

**Issue by diguage** [tupadr3/plantuml-icon-font-sprites#31]
This set of icons is awesome! Thanks!

**Could you convert the PNG images to SVG images?** 

SVG images are not distorted when enlarged. This way it can be used in more places.

**Comment by tupadr3** [comment]
The project already supports generating icons in SVG format, but the generated files are not included in the repository. The PNG files are only incorporated for reference purposes within the documentation.

To create the SVG files, use the following command:
```bash
node ./src/lib/index.js --fonts weather --formats svg
```
You can locate the generated SVG files in the `.tmp/build/weather/svg` directory.
