### ISSUE TITLE
Icon Request: Azure

### ISSUE THREAD

**Issue by Dominic-Preap** [tupadr3/plantuml-icon-font-sprites#32]
I would like to request a new sprite be added for the Microsoft Azure.

See: https://devicon.dev/ and search **azure**

![image](https://github.com/tupadr3/plantuml-icon-font-sprites/assets/14802170/03bf58de-7d69-4b8d-9561-9482917bf265)

**Comment by tupadr3** [comment]
The latest version v3.0.0 contains the latest devicons2 version, which includes the azure icon.
