### ISSUE TITLE
https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0 produces an 400: Invalid request

### ISSUE THREAD

**Issue by maximatt** [tupadr3/plantuml-icon-font-sprites#34]
Hi, I getting a little issue with some diagrams

`https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0`

retrieves a:

`400: Invalid request`

**Comment by Potherca** [comment]
By itself `https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0` does not exist. It needs to be combined with an existing file. For instance `common.puml`: view-source:https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0/common.puml

As per the example in the README:

```
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml
```

Without further code it is hard to tell what might be the problem. Could you post the (part of the) code that is giving you issues?
